# Config file for automatic testing at travis-ci.org

language: python

# Use container based infrastructure
sudo: false

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

env:
  matrix:
    - DJANGO=1.6 CMD=./test
    - DJANGO=1.7 CMD=./test

matrix:
  allow_failures:
    - python: 3.3
    - python: 3.4
  fast_finish: true
  include:
    - python: 2.7
      env: DJANGO=1.6 CMD="flake8 aldryn_people"

install:
  - pip install -q -r "test_requirements/django-$DJANGO.txt"

script: coverage run test_settings.py

after_success: coveralls
