language: python

python: 3.5

sudo: false

env:
  global:
    # encrypted Sauce Labs sub-account user name
    - secure: OIkBwlWwClimhBeKs4kT4Elkp9fx+pjEBKJlZY+TpIXsjqskKgSbsnDkBcQuW9cJoj4qCddRAKOzN/XD3tT+ZAbo/257lSMcDCdslqxehd/JJVCfglANGioMxHUmZ9F5EDrc+ZtnQ40O5tcFNHRgJXR92el931V379zs/9om8LY=
    # encrypted Sauce Labs sub-account token
    - secure: MWxL/6t1qI3TSIcBDDMtctIlvXjJtOCxMk0Xj4I7vzE5jvhBMhHT+1YBR8Wd8AykzbTmK5XAe4jhhBmlHannm5zRfmua9D+kpvGQH819V46setzluConoXTgPMWE7O9gtVeOiNBuLGD72ELO/X8ZbiYcO/JFsXbad5tNQZ3XTJo=
    # encrypted Code Climate token
    - secure: oJG/hKhutnzSFCSF8xUuMWmTxeuRp2eU9HBi/7JWVxd3AwDkKu3jtldQ0Vg/2iSofRzzG0wZpUKdgGa4ObOpOou5wWtq68OAVbJkHAtOB7U3HR4deVuQRZdR8GXWWS9G+H1B8PbFCVPzQrsnxHs/k0oBLUgAW8XfFfkhzzYGFKk=
  matrix:
    # Matrix-size reduction strategies:
    #   PY strategy: do not test 3.3 at all.
    #   FE strategy: only test on Django/CMS3.3 combinations, but place tests on
    #                different Python ENVs if possible.
    - TOXENV=flake8

    - TOXENV=py35-dj110-cms35
    - TOXENV=py35-dj110-cms34
    - TOXENV=py34-dj110-cms35
    - TOXENV=py34-dj110-cms34
    - TOXENV=py27-dj110-cms35
    - TOXENV=py27-dj110-cms34

    - TOXENV=py35-dj19-cms34
    - TOXENV=py35-dj19-cms33
    - TOXENV=py35-dj19-cms32
    - TOXENV=py34-dj19-cms34
    - TOXENV=py34-dj19-cms33
    - TOXENV=py34-dj19-cms32
    - TOXENV=py27-dj19-cms34
    - TOXENV=py27-dj19-cms33
    - TOXENV=py27-dj19-cms32
    # - TOXENV=py35-dj19-cms33-fe FE=1

    - TOXENV=py35-dj18-cms34
    - TOXENV=py35-dj18-cms33
    - TOXENV=py35-dj18-cms32
    - TOXENV=py34-dj18-cms34
    - TOXENV=py34-dj18-cms33
    - TOXENV=py34-dj18-cms32
    - TOXENV=py27-dj18-cms34
    - TOXENV=py27-dj18-cms33
    - TOXENV=py27-dj18-cms32
    # - TOXENV=py27-dj18-cms33-fe FE=1

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip install tox
  - pip install coveralls

before_script:
  - if [ "$FE" == 1 ]; then nvm install 6 && nvm use 6; fi
  - if [ "$FE" == 1 ]; then npm config set spin false; fi
  - if [ "$FE" == 1 ]; then npm install -g gulp@3.9.0; fi
  - if [ "$FE" == 1 ]; then npm install -g codeclimate-test-reporter; fi
  - if [ "$FE" == 1 ]; then npm install; fi

script:
  - tox -e $TOXENV

after_script:
  - codeclimate < tests/coverage/**/lcov.info

after_success: coveralls

notifications:
  webhooks: http://addons.us-iad-rs.aldryn.io/en/travis-endpoint/
