language: python

python: 3.5

sudo: false

env:
  global:
    # encrypted Sauce Labs sub-account user name
    - secure: OIkBwlWwClimhBeKs4kT4Elkp9fx+pjEBKJlZY+TpIXsjqskKgSbsnDkBcQuW9cJoj4qCddRAKOzN/XD3tT+ZAbo/257lSMcDCdslqxehd/JJVCfglANGioMxHUmZ9F5EDrc+ZtnQ40O5tcFNHRgJXR92el931V379zs/9om8LY=
    # encrypted Sauce Labs sub-account token
    - secure: MWxL/6t1qI3TSIcBDDMtctIlvXjJtOCxMk0Xj4I7vzE5jvhBMhHT+1YBR8Wd8AykzbTmK5XAe4jhhBmlHannm5zRfmua9D+kpvGQH819V46setzluConoXTgPMWE7O9gtVeOiNBuLGD72ELO/X8ZbiYcO/JFsXbad5tNQZ3XTJo=
    # encrypted Code Climate token
    - secure: oJG/hKhutnzSFCSF8xUuMWmTxeuRp2eU9HBi/7JWVxd3AwDkKu3jtldQ0Vg/2iSofRzzG0wZpUKdgGa4ObOpOou5wWtq68OAVbJkHAtOB7U3HR4deVuQRZdR8GXWWS9G+H1B8PbFCVPzQrsnxHs/k0oBLUgAW8XfFfkhzzYGFKk=

matrix:
  include:
    - python: '3.5'
      env: TOXENV=flake8
    - python: '3.6'
      env: TOXENV=py36-dj111-cms35
    - python: '3.5'
      env: TOXENV=py35-dj111-cms35
    - python: '3.5'
      env: TOXENV=py35-dj110-cms34
    - python: '3.5'
      env: TOXENV=py35-dj19-cms34-reversion
    - python: '3.5'
      env: TOXENV=py35-dj19-cms34
    - python: '3.5'
      env: TOXENV=py35-dj19-cms33-fe FE=1
    - python: '2.7'
      env: TOXENV=py27-dj111-cms34
    - python: '2.7'
      env: TOXENV=py27-dj110-cms34
    - python: '2.7'
      env: TOXENV=py27-dj19-cms34
    - python: '2.7'
      env: TOXENV=py27-dj19-cms33
    - python: '2.7'
      env: TOXENV=py27-dj19-cms32
    - python: '3.5'
      env: TOXENV=py35-dj18-cms34-reversion
    - python: '3.5'
      env: TOXENV=py35-dj18-cms34
    - python: '3.5'
      env: TOXENV=py35-dj18-cms33
    - python: '3.5'
      env: TOXENV=py35-dj18-cms32
    - python: '2.7'
      env: TOXENV=py27-dj18-cms34
    - python: '2.7'
      env: TOXENV=py27-dj18-cms33-fe FE=1
    - python: '2.7'
      env: TOXENV=py27-dj18-cms32
  allow_failures:
    - python: '2.7'
      env: TOXENV=py27-dj18-cms33-fe FE=1
    - python: '3.5'
      env: TOXENV=py35-dj19-cms33-fe FE=1

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip install tox
  - pip install coveralls

before_script:
  - if [ "$FE" == 1 ]; then nvm install 0.12.7 && nvm use 0.12.7; fi
  - if [ "$FE" == 1 ]; then npm config set spin false; fi
  - if [ "$FE" == 1 ]; then npm install -g npm@2; fi
  - if [ "$FE" == 1 ]; then npm install -g gulp@3.9.0; fi
  - if [ "$FE" == 1 ]; then npm install -g codeclimate-test-reporter; fi
  - if [ "$FE" == 1 ]; then npm install; fi

script:
  - tox -e $TOXENV

after_script:
  - codeclimate < tests/coverage/**/lcov.info

after_success: coveralls

notifications:
  webhooks: http://addons.us-iad-rs.aldryn.io/en/travis-endpoint/
